name: todo_moura
description: "Projeto de demonstração de um app de tarefas"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_bloc: ^8.1.0
  sqflite: ^2.2.8+1
  path_provider: ^2.0.15
  get_it: ^7.6.7
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

